//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace childrens_hospitall.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Patient = new HashSet<Patient>();
        }
    
        public int id_staff { get; set; }
        public string fname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string speciality { get; set; }
        public string name_speciality { get; set; }
        public string name_kvalivication { get; set; }
        public Nullable<int> id_position { get; set; }
        public Nullable<int> id_diplom { get; set; }
        public Nullable<int> staj { get; set; }
        public Nullable<int> id_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patient { get; set; }
        public virtual Position Position { get; set; }
        public virtual user user { get; set; }
    }
}
